apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # Puerto del servicio
      targetPort: 27017 # Puerto del contenedor
  type: ClusterIP