apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: unir-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: mongo-config
                optional: false
            - secretRef:
                name: mongo-secret
                optional: false
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - emptyDir: {}
          name: mongo-data